name: IAC Terraform

on:
    push:
      branches:
        - main
      paths:
        - 'terraform/**/*.tf'
        - 'terraform/**/*.tfvars'
  

jobs:
  deploy:
    name: Push to EC2 Prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      # Step 2: Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform/prod
        run: terraform init

      # Step 3: Validate Terraform
      - name: Terraform Validate
        working-directory: ./terraform/prod
        run: terraform validate

      # Step 4: Generate Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform/prod
        run: terraform plan -out=tfplan

      # Step 5: Apply Terraform Plan
      - name: Apply with Approval
        working-directory: ./terraform/prod
        run: |
          terraform apply -auto-approve tfplan
          terraform output -raw ec2_public_dns > ec2_dns.txt