name: 'Main Pipeline-CI/CD'

on:
  push:
    branches:
      - main
      - staging
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - 'src/**'
      - '.github/workflows/*.yml'
      - './'

jobs:
  ci-test:
    uses: ./.github/workflows/ci.yml

  terraform:
    needs: ci-test
    uses: ./.github/workflows/iac.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}