name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Add the SSH host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # Ensure this is the correct public IP of your EC2 instance
          username: ec2-user  # Ensure this matches the correct username for your instance
          key: ${{ secrets.EC2_SSH_KEY }}  # Use the secret key stored in GitHub Secrets
          source: "./your-local-directory/*"
          target: "/remote/directory"
