name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  check_terraform_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Check if Terraform Infrastructure workflow is running
        id: check_terraform_running
        run: |
          echo "Checking if Terraform Infrastructure workflow is running..."
          # Use the GitHub CLI to list the workflow runs
          IAC_RUNNING=$(gh run list --workflow="Terraform Infrastructure" --status "in-progress" --json status --jq '. | length')
          echo "IAC_RUNNING=${IAC_RUNNING}" >> $GITHUB_ENV

  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    needs: check_terraform_status
    if: needs.check_terraform_status.outputs.iac_running == '0'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.0"
          terraform_wrapper: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

      - name: Terraform Init and Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
         terraform init
         terraform apply -auto-approve
         DNS=$(terraform output -raw ec2_public_dns)
         echo "EC2_PUBLIC_DNS=$DNS" >> $GITHUB_ENV

      # Add your deployment or SSH steps here
      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           SOURCE: "./"
           REMOTE_HOST: ${{ env.EC2_PUBLIC_DNS }}
           REMOTE_USER: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
           host: ${{ env.EC2_PUBLIC_DNS }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
                sudo apt-get update -y

                curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                sudo apt-get install -y nodejs

                cd /home/ubuntu/app/my-app

                npm install

                npm run build

                pm2 delete all

                pm2 start npm --name "nextjs-app" -- start
