name: Prod Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "prod-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    name: Push to EC2 Prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download EC2 DNS Artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-dns-output

      - name: Set EC2 Public DNS as Env Variable
        run: |
          EC2_PUBLIC_DNS=$(cat ec2_dns.txt)
          echo "DNS=$EC2_PUBLIC_DNS" >> $GITHUB_ENV


      # Step 6: Deploy Files to the Server
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "./my-app"
          REMOTE_HOST: ${{ env.DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 7: Execute Remote SSH Commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo apt-get update -y

            # Install Node.js and npm
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Navigate to the project directory
            cd /home/ubuntu/app/my-app

            # Install project dependencies
            npm install

            # Build the Next.js project
            npm run build

            # Install PM2 globally
            sudo npm install -g pm2
            pm2 delete all

            # Start the Next.js app with PM2
            pm2 start npm --name "nextjs-app" -- start