name: Prod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Prod
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      # Step 2: Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform/prod
        run: terraform init

      # Step 3: Validate Terraform
      - name: Terraform Validate
        working-directory: ./terraform/prod
        run: terraform validate

      # Step 4: Generate Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform/prod
        run: terraform plan -out=tfplan

      # Step 5: Apply Terraform Plan
      - name: Apply with Approval
        working-directory: ./terraform/prod
        run: |
          terraform apply -auto-approve tfplan
          DNS=$(terraform output -raw ec2_public_dns)
          echo "EC2_PUBLIC_DNS=$DNS" >> $GITHUB_ENV

      # Step 6: Deploy to EC2 instance
      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ env.EC2_PUBLIC_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 7: Execute remote SSH commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ env.EC2_PUBLIC_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get update -y

            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

            cd /home/ubuntu/app/my-app

            npm install

            npm run build

            sudo npm install -g pm2

            pm2 delete all

            pm2 start npm --name "nextjs-app" -- start