name: Merge to Staging

on:
    workflow_call:

permissions:
  contents: write

jobs:
  merge_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'

    - name: Checkout staging branch
      run: git checkout staging

    - name: Merge main branch into staging
      run: git merge -X theirs main

    - name: Commit the merge
      run: git commit -m "Merge Branch" || echo "Nothing to commit"

    - name: Push changes to remote
      run: git push origin staging
