name: Terraform Deploy to Staging

on:
  push:
    branches:
      - staging  # Trigger when there’s a push to the staging branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"  # You can use the version you prefer

      - name: Change directory to terraform
        run: cd terraform

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Plan Terraform deployment
        working-directory: ./terraform
        run: terraform plan

     