name: Terraform Deploy to Staging

on:
  push:
    branches:
      - staging  # Trigger when there’s a push to the staging branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"  # You can use the version you prefer

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform deployment
        run: terraform plan

      - name: Apply Terraform deployment
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
