name: VPC Deploy

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    name: Push to VPC EC@
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      - name: Set Environment Variables
        working-directory: ./terraform/final
        run: |
            echo "TF_VAR_FILE=env/production/terraform.tfvars" >> $GITHUB_ENV    
      # Step 2: Initialize Terraform
      - name: Initialize Terraform
        working-directory: ./terraform/final
        run:  |
           terraform init
              # terraform destroy -auto-approve -var-file=env/production/terraform.tfvars
              # rm -f terraform.tfstate terraform.tfstate.backup

      # Step 3: Validate Terraform
      - name: Terraform Validate
        working-directory: ./terraform/final
        run: terraform validate

      # Step 4: Generate Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform/final
        run: terraform plan -out=tfplan -var-file=env/production/terraform.tfvars

      # Step 5: Apply Terraform Plan
      - name: Apply with Approval
        working-directory: ./terraform/final
        run: |
          terraform apply -auto-approve tfplan
      # #     # IP=$(terraform output -raw ec2_public_ip)
      #     # echo "EC2_IP=$IP" >> $GITHUB_ENV

      # Step 6: Deploy to EC2 instance
      # - name: Deploy to EC2 instance
      #   uses: easingthemes/ssh-deploy@v2.1.5
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     SOURCE: "./my-app"
      #     REMOTE_HOST: ${{ env.EC2_IP }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     TARGET: ${{ secrets.TARGET_DIR }}

      # - name: Execute remote SSH commands
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ env.EC2_IP }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo apt-get update -y

      #       curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      #       sudo apt-get install -y nodejs

      #       cd /home/ubuntu/app/my-app

      #       npm install

      #       npm run build

      #       sudo npm install -g pm2

      #       pm2 delete all

      #       pm2 start npm --name "nextjs-app" -- start
